# Цвет триггерных замен:
# BLACK
# DARK_BLUE
# DARK_GREEN
# DARK_AQUA
# DARK_RED
# DARK_PURPLE
# GOLD
# GRAY
# DARK_GRAY
# BLUE
# GREEN
# AQUA
# RED
# LIGHT_PURPLE
# YELLOW
# WHITE

trigger-color: GREEN

triggers:
  xyz:
    - "xyz"
    - "координаты"
    - "кордах"

  item:
    - "item"
    - "предмет"

  random:
    - "random"
    - "рандом"